services:
  nginx:
    image: nginx:alpine
    container_name: up_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./tls:/etc/letsencrypt
      - ./webroot:/var/www/certbot
      
  certbot:
    image: certbot/certbot
    container_name: up_certbot
    volumes:
      - ./tls:/etc/letsencrypt
      - ./webroot:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot || true; sleep 12h & wait $${!}; done;"
    restart: unless-stopped
    depends_on:
      - nginx 